site_name: 3DS Hacks Guide
theme: 
    name: slate
    custom_dir: custom_dir/
copyright: Copyright &copy; 2021 <a href="https://discord.gg/C29hYvh" target="_blank">Nintendo Homebrew</a>, Maintained by the <a href="/Guide-3DS_mkdocs/credits">NH Discord Server</a>.
site_description: 3DS Hacks Guide.
site_author: NH Discord Server.

nav:
    - Home: index.md
    - User Guide:
        - 'Get Started': 'user-guide/get-started.md'
        - Methods: 
            - 'Soundhax': 'user-guide/installing-boot9strap-(soundhax).md'  
            - 'Browser' : 'user-guide/installing-boot9strap-(browser).md'
        - 'Finalizing Setup': finalizing-setup.md
    - Extras:
        - 'A9LH to B9S': 'extras/a9lh-to-b9s.md'
        - 'CTRtransfer': 'extras/ctrtransfer.md'
        - 'GodMode9 Usage': 'extras/godmode9-usage.md'
        - 'Restoring CFW': 'extras/restoring-cfw.md'
        - 'Updating B9S': 'extras/updating-b9s.md'
    - FAQ: faq.md
    - Credits: credits.md
    
markdown_extensions:
    - admonition
    - fontawesome_markdown

extra_css:
    - css/custom.css
