site_name: 3DS Hacks Guide
theme: 
    name: mkdocs
    custom_dir: custom_dir/
copyright: Copyright &copy; 2021 <a href="https://discord.gg/C29hYvh" target="_blank">Nintendo Homebrew</a>, Maintained by the <a href="/switch-guide/about">NH Discord Server</a>.
site_description: 3DS Hacks Guide.
site_author: NH Discord Server.
site_url: https://lifehackerhansol.github.io/Guide-3DS_mkdocs/
repo_url: https://github.com/lifehackerhansol/Guide-3DS_mkdocs/

nav:
    - Home: index.md
    - User Guide:
        - 'Get Started': 'user-guide/get-started.md'
        - Methods: 
            - 'Soundhax': 'user-guide/installing-boot9strap-(soundhax).md'  
            - 'Browser' : 'user-guide/installing-boot9strap-(browser).md'
        - 'Finalizing Setup': finalizing-setup.md
    - Extras:
        - 'Blocking Updates': 'extras/blocking_updates.md'
        - 'Restoring a NAND Backup': 'extras/nandrestore.md'
        - 'AutoRCM': 'extras/autorcm.md'
        - 'Dumping Title Keys': 'extras/dumping_title_keys.md'
        - 'Theming': 'extras/theming.md'
        - 'Save Management': 'extras/save_management.md'
        - 'Game Modding': 'extras/game_modding.md'       
        - 'Linux injection without root': 'extras/adding_udev.md'
        - 'Showing File Name Extensions (Windows)': 'extras/showing_file_extensions.md'
        - 'Alternate Boot Setups': 'extras/alternate_bootsetups.md'
        - 'RCM Payload Injectors Information': 'extras/rcm_injectors.md'
        - 'Updating CFW': 'extras/updating.md'
        - 'Changing SD cards': 'extras/transfer_sd.md'
        - 'Glossary': 'extras/glossary.md'
    - FAQ: faq.md
    - About: about.md
    
markdown_extensions:
    - admonition
    - fontawesome_markdown

extra_css:
    - css/custom.css
